# Generated by Django 5.1.4 on 2025-01-03 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_studentmodel_last_login_alter_studentmodel_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
